
import jsPDF from 'jspdf';
import { Customer, Transaction } from '../types/admin';
import { formatCurrency } from './adminUtils';

// Add Divine Mobile logo to PDF with consistent branding
const addDivineMobileLogo = (doc: jsPDF, x: number, y: number, width: number = 50, height: number = 16) => {
  // Create the rounded purple background for the logo
  doc.setFillColor(79, 70, 229); // Blue color matching the brand
  doc.roundedRect(x, y, width, height, 4, 4, 'F');
  
  // Add mobile phone icon representation
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(x + 4, y + 3, 10, 10, 2, 2, 'F');
  doc.setFillColor(79, 70, 229);
  doc.roundedRect(x + 5, y + 4, 8, 8, 1, 1, 'F');
  doc.setFillColor(255, 255, 255);
  doc.circle(x + 9, y + 6, 0.5, 'F');
  doc.rect(x + 6, y + 7, 6, 4, 'F');
  
  // Add "Divine Mobile" text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Divine', x + 16, y + 8);
  doc.setTextColor(147, 197, 253); // Light blue for "Mobile"
  doc.text('Mobile', x + 16, y + 13);
  
  // Reset colors
  doc.setTextColor(0, 0, 0);
};

export const generateCustomerReport = (customer: Customer, customerTransactions: Transaction[], toast: any) => {
  const doc = new jsPDF();
  
  // Add Divine Mobile logo
  addDivineMobileLogo(doc, 20, 15);
  
  // Header
  doc.setFontSize(20);
  doc.text('OneCard Customer Report', 80, 25);
  doc.setFontSize(12);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 80, 35);
  
  // Customer Info
  doc.setFontSize(16);
  doc.text('Customer Information', 20, 55);
  doc.setFontSize(11);
  doc.text(`Name: ${customer.firstName} ${customer.lastName}`, 20, 70);
  doc.text(`Email: ${customer.email}`, 20, 80);
  doc.text(`Phone: ${customer.phone}`, 20, 90);
  doc.text(`Card Number: ${customer.cardNumber}`, 20, 100);
  doc.text(`Registration Date: ${new Date(customer.registrationDate).toLocaleDateString()}`, 20, 110);
  doc.text(`Network Provider: ${customer.networkProvider}`, 20, 120);
  doc.text(`RICA Verified: ${customer.ricaVerified ? 'Yes' : 'No'}`, 20, 130);
  
  // Financial Summary
  doc.setFontSize(16);
  doc.text('Financial Summary', 20, 150);
  doc.setFontSize(11);
  doc.text(`OneCard Balance: ${formatCurrency(customer.onecardBalance)}`, 20, 165);
  doc.text(`Total Cashback Earned: ${formatCurrency(customer.totalCashback)}`, 20, 175);
  doc.text(`Total Transactions: ${customerTransactions.length}`, 20, 185);
  
  const totalSpent = customerTransactions.reduce((sum, tx) => sum + (Number(tx.amount) || 0), 0);
  doc.text(`Total Amount Spent: ${formatCurrency(totalSpent)}`, 20, 195);
  
  // Recent Transactions
  if (customerTransactions.length > 0) {
    doc.setFontSize(16);
    doc.text('Recent Transactions', 20, 215);
    doc.setFontSize(9);
    
    let yPos = 230;
    customerTransactions.slice(0, 10).forEach((tx, index) => {
      if (yPos > 270) {
        doc.addPage();
        addDivineMobileLogo(doc, 20, 15); // Add logo to new page
        yPos = 35;
      }
      const network = tx.network || 'N/A';
      const status = tx.status || 'N/A';
      doc.text(`${new Date(tx.timestamp).toLocaleDateString()} - ${network} - ${formatCurrency(tx.amount)} - ${status}`, 20, yPos);
      yPos += 10;
    });
  }
  
  // Footer with Divine Mobile branding
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Divine Mobile OneCard Platform', 20, doc.internal.pageSize.height - 10);
  
  doc.save(`Divine_Mobile_OneCard_Report_${customer.firstName}_${customer.lastName}_${new Date().toISOString().split('T')[0]}.pdf`);
  
  toast({
    title: "Report Generated",
    description: `Customer report for ${customer.firstName} ${customer.lastName} has been downloaded.`,
    duration: 3000,
  });
};

export const generateMasterReport = (customers: Customer[], transactions: Transaction[], toast: any) => {
  const doc = new jsPDF();
  
  // Add Divine Mobile logo
  addDivineMobileLogo(doc, 20, 15);
  
  // Header
  doc.setFontSize(20);
  doc.text('OneCard Master Report', 80, 25);
  doc.setFontSize(12);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 80, 35);
  
  // Summary Statistics
  doc.setFontSize(16);
  doc.text('Platform Overview', 20, 55);
  doc.setFontSize(11);
  doc.text(`Total Customers: ${customers.length}`, 20, 70);
  doc.text(`Total Active Cards: ${customers.length}`, 20, 80);
  
  const totalBalance = customers.reduce((sum, customer) => sum + (Number(customer.onecardBalance) || 0), 0);
  const totalCashback = customers.reduce((sum, customer) => sum + (Number(customer.totalCashback) || 0), 0);
  const totalTransactions = transactions.length;
  const totalRevenue = transactions.reduce((sum, tx) => sum + (Number(tx.amount) || 0), 0);
  
  doc.text(`Total Platform Balance: ${formatCurrency(totalBalance)}`, 20, 90);
  doc.text(`Total Cashback Distributed: ${formatCurrency(totalCashback)}`, 20, 100);
  doc.text(`Total Transactions: ${totalTransactions}`, 20, 110);
  doc.text(`Total Revenue: ${formatCurrency(totalRevenue)}`, 20, 120);
  
  // Network Breakdown
  const networkStats = customers.reduce((stats, customer) => {
    const network = customer.networkProvider || 'Unknown';
    stats[network] = (stats[network] || 0) + 1;
    return stats;
  }, {} as Record<string, number>);
  
  doc.setFontSize(16);
  doc.text('Network Distribution', 20, 140);
  doc.setFontSize(11);
  let yPos = 155;
  Object.entries(networkStats).forEach(([network, count]) => {
    doc.text(`${network}: ${count} customers`, 20, yPos);
    yPos += 10;
  });
  
  // Customer List
  doc.addPage();
  addDivineMobileLogo(doc, 20, 15); // Add logo to new page
  doc.setFontSize(16);
  doc.text('Customer Directory', 20, 35);
  doc.setFontSize(9);
  
  yPos = 50;
  customers.forEach((customer, index) => {
    if (yPos > 270) {
      doc.addPage();
      addDivineMobileLogo(doc, 20, 15); // Add logo to new page
      yPos = 35;
    }
    doc.text(`${customer.cardNumber} - ${customer.firstName} ${customer.lastName} - ${formatCurrency(customer.onecardBalance)}`, 20, yPos);
    yPos += 8;
  });
  
  // Footer with Divine Mobile branding
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Divine Mobile OneCard Platform', 20, doc.internal.pageSize.height - 10);
  
  doc.save(`Divine_Mobile_OneCard_Master_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  
  toast({
    title: "Master Report Generated",
    description: "Complete platform report has been downloaded.",
    duration: 3000,
  });
};
