// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faubmvkpcgjxmzemztye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdWJtdmtwY2dqeG16ZW16dHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDU3MjQsImV4cCI6MjA2NDI4MTcyNH0.WscnDVE8o9J1waP4JDxsr0BRzLvtwWi2RMPotSbgb9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);